### ISSUE TITLE
Asset library bad hash

### ISSUE THREAD

**Issue by ohmree** [godot-extended-libraries/abstract-state-machine#1]
**Describe the bug**
When I try to download the addon from the AssetLib I get an error about the download hash being different from the expected hash.

**To Reproduce**
1. Open a project
2. Go to the AssetLib tab
3. Search for "state machine"
4. Click on this addon
5. Hit download
6. See error

**Expected behavior**
The addon should get downloaded & installed without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13455401/78369664-3a4c1980-75ce-11ea-84ed-b81774a21b84.png)

**Versions:**
 - OS: Windows 10
 - Godot: 3.2.1

**Comment by nonunknown** [comment]
https://github.com/godot-extended-libraries/abstract-state-machine/releases Here you can download the latest release, since Assetlib does not updated it!

**Comment by nonunknown** [comment]
Also I've tested downloading from webbrowser assetlib and downloaded fine, I'll take a look into this, tkx

**Comment by nonunknown** [comment]
![Screenshot from 2020-04-03 19-42-31](https://user-images.githubusercontent.com/58845030/78410641-527a6380-75e3-11ea-9629-778fd6a57cdc.png)

as Calinou has said, it was fixed
